import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { Container } from '@mui/material';
import { SessionProvider } from '../context/SessionProvider';
import { ApolloClientProvider } from '@/components/ApolloWrapper';
import { Header } from '@/components/layout/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <AppRouterCacheProvider>
          <SessionProvider>
            <ApolloClientProvider>
              <ThemeProvider theme={theme}>
                <Header />
                <Container maxWidth="sm" className="mt-6">
                  {children}
                </Container>
              </ThemeProvider>
            </ApolloClientProvider>
          </SessionProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
